### ISSUE TITLE
User friendliness of algerbas and interpreters composition

### ISSUE THREAD

**Issue by Krever** [julienrf/endpoints#29]
Currently,  we have a lot of different traits in different modules that can be used to create algebra/server/client and for someone to know what he can use he need to basically browse through source of the library. I think it would be good to address this problem. 
What we have now:
```scala
import endpoints._
trait ApiAlg extends EndpointAlg with CirceCodecAlg with AssetAlg
  with OptionalResponseAlg with BasicAuthenticationAlg 

object Api extends ApiAlg with EndpointPlayRouting with CirceCodecPlayRouting with AssetPlayRouting
  with OptionalResponsePlayRouting with BasicAuthenticationPlayRouting

object Api extends ApiAlg with EndpointXhrClient with CirceCodecXhrClient with AssetXhrClient
  with XhrClientThenable with OptionalResponseXhrClient with BasicAuthenticationXhrClient
```
So to create this, user need to know at least 16 different traits that are not documented anywhere(so need to look at them in the source code, where he will find a lot of supporting traits(UrlAlg, MethodAlg, etc) that are not separated in any way;

I think there are few things we can do:

1. Organise traits in feature-orientend package naming way:
```scala
import endpoints._
trait ApiAlg extends endpoints.Algebra with assets.Algebra
  with optinalresposne.Algebra with authentication.basic.Algebra with marshalling.Circe

object Api extends ApiAlg with routing.Play with routing.play.Circe with routing.play.Assets
  with routing.play.OptionalResponse with routing.play.BasicAuthentication

object Api extends ApiAlg with client.Xhr with client.xhr.Circe with client.xhr.Assets
  with client.xhr.Thenable with client.xhr.OptionalResponse with client.xhr.BasicAuthentication
```
It allows to more intuitive browsing of possibilities, increase readability and divide traits between more descriptive packages. All non user-facing traits should probably go to e.g. `client.xhr.Internal` or something like that.

2. Document the choices:

We should probably do it somehow, probably some list of all available Algebras with their implementations. But I have completely no idea how such list should look like, because e.g `JsonEntityAlg` is partially implemented in `CirceCodecAlg` and partially in external modules. 

3. Encourage composition instead of inheritance

I don't know if it is even possible, but if we define `ApiAlg` like this:
 ```scala
import endpoints._
class ApiAlg(
  endpointAlg: EndpointAlg,
  circeCodecAlg: CirceCodecAlg,
  assetsAlg: AssetAlg,
  optionalResponseAlg: OptionalResponseAlg,
  basicAuthAlgebra: BasicAuthenticationAlg
) {
  import endpointAlg._
  import circeCodecAlg._
  import assetsAlg._
  import optionalResponseAlg._
  import basicAuthAlgebra._
  
  ???
  } 
```
It would much easier to define server and client, because all algebras, that we need to provide support for are listed explicitly. I know that converting from trait to class removes almost all extensibility, but maybe we should support both styles or find some other solution? As I said, I didn't event check if it would work, but in scala we can do almost anything :)

All of these are rather ideas then concrete proposals, so I would like to discuss it before starting any implementation. All names I have used are not concrete proposals too :)

**Comment by julienrf** [comment]
> 1. Organise traits in feature-orientend package naming way

Currently the naming strategy is to:
- suffix algebra interfaces with `Alg` (e.g. `EndpointAlg`) ;
- introduce a distinct suffix for each kind of interpreter (e.g. `PlayRouting` or `XhrClient`) ;
- when an interface is implemented by an interpreter, we name this trait by taking the algebra interface and replacing the `Alg` suffix with the interpreter name (e.g. `EndpointPlayRouting` or `EndpointXhrClient`).

The idea is to get the following benefits, assuming that at some point we would publish a scaladoc unified across these modules:
1. being able to easily look for algebra interfaces by looking for traits suffixed by `Alg` (in your proposal, that would be more or less the same, but we would look for trait named `Algebra` instead) ;
2. each interpreter fixes (at least some of the) abstract type members of the algebra interface, and the idea here is that the following convention should hold: all the interpreter traits that share the same suffix should have compatible types (in your proposal, this convention is based on the package names instead, but is more or less the same I think) ;
3. being able to find interpreters of a given algebra interface by looking for traits that start with the same name as the algebra interface name (in your proposal I think we would loose this ability).

I would be happy to revisit the current naming convention but I’d like to find a solution that maintains the 3rd point listed above.

> 2. Document the choices

Yes! That’s definitely something I would love to have. At least, having a simple table like the following could help :

| Algebra interface | Description | Interpreters |
|------------------------|-----------------|------------------|
| `EndpointAlg` | HTTP endpoints | `EndpointPlayRouting`, `EndpointPlayClient`, etc. |
| `AssetAlg` | Static assets | `AssetPlayRouting`, `AssetXhrClient` |
| `JsonEntityAlg` | JSON request and response entities | `JsonEntityPlayRoutingCirce`, `JsonEntityXhrClientCirce` |
| `CirceCodecAlg` | JSON entities based on [circe](http://github.com/travisbrown/circe) codecs | `CirceCodecPlayRouting`, `CirceCodecXhrClient` |

But there are so many ways to navigate through these DSLs that this simple table would not be enough, for instance it would be interesting to know, given an algebra interface, what are the other algebra interfaces that extend it, or the algebra interfaces this one depends on. Also, it would be interesting to group interpreters by the concrete representation they use (e.g. all the interpreters suffixed by `PlayRouting`).

We could probably fix this by having two more tables, one for the algebra interfaces and one for the interpreters.

| Algebra interface | Parent interfaces |
|------------------------|------------------------|
| `EndpointAlg`    |  `UrlAlg`, `MethodAlg` |
| `AssetAlg`    | `EndpointAlg` |
| `JsonEntityAlg` | `EndpointAlg` |

And:

| Interpreter | Description | Implemented interfaces |
|---------------|---------------|------------------------|
| `PlayRouting` | serves the endpoints (backed by Play framework) | `EndpointPlayRouting`, `AssetPlayRouting`, etc. |
| `AkkaRouting` | serves the endpoints (backed by Akka-HTTP) | `EndpointAkkaRouting`, `AssetAkkaRouting`, etc. |
| `XhrClient` | Scala.js client for the endpoints (uses XMLHttpRequest under the hood) | `EndpointXhrClient`, `AssetXhrClient`, etc. |
| `Blueprint` | documents the endpoints (produces an [API bueprint](https://apiblueprint.org/)) | `EndpointBlueprint`, `AssetBlueprint`, etc. |

I admit that reading these tables is awkward. So, it would be even better to have an interactive way to navigate into this information (e.g. given an interface, being able to list all its interpreters, and given a “kind” of interpreter being able to list all its implemented interfaces, etc.).

Note that this discussion is related to #10.

> 3. Encourage composition instead of inheritance

Ah, unfortunately your example would not work for the following reasons:
- all the parameters have to agree on the same concrete representation of the abstract type members (e.g. the concrete `Request[A]` of the `AssetAlg` must be the same as the one of the `EndpointAlg`) ;
  - enforcing this constraint would lead to adding the following kind of refinements:
    ~~~ scala
    class ApiAlg(endpointAlg: EndpointAlg)(assetAlg: AssetAlg { type Request[A] = endpointAlg.Request[A]; type Response[A] = endpointAlg.Response[A]; … })
    ~~~
- class constructors do not work with dependent types ([SI-5712](https://issues.scala-lang.org/browse/SI-5712)).

Maybe at some point, when dotty will be ready, we will be able to advantageously replace our cake pattern with something based on typeclasses and [implicit functions](http://www.scala-lang.org/blog/2016/12/07/implicit-function-types.html) to handle composition instead of traits and inheritance…

**Comment by Krever** [comment]
Thanks for all the answers!

> I would be happy to revisit the current naming convention but I’d like to find a solution that maintains the 3rd point listed above.

Ok, I will try to figure something out to keep this possibility. I like very much the cohesion of current rules, but not having explicit separators in names make it really hard to read and browse. 

> So, it would be even better to have an interactive way to navigate into this information

Maybe some sort of graph? The biggest problem with graphs is representation that will be easy to maintain. I will try to generate something with graphviz(unless you know some better tools for things like that) and post it in #10 .

> Ah, unfortunately your example would not work:

That's sad. Thanks for explaination.

**Comment by Krever** [comment]
I came up with 3 ideas for naming, but I cannot easily say if any of them gives some real profit. 

0. `FeatureFramework` (current)
1. `feature.framework.Support`
2. `feature.FrameworkSupport`
3. `framework.Feature`

Examples:
0. `FeatureFramework` (current)
```scala
trait ApiAlg extends EndpointAlg with CirceCodecAlg with AssetAlg with OptionalResponseAlg with BasicAuthenticationAlg

object Api extends ApiAlg with EndpointPlayRouting with CirceCodecPlayRouting with AssetPlayRouting with OptionalResponsePlayRouting with BasicAuthenticationPlayRouting

object Api extends ApiAlg with EndpointXhrClient with CirceCodecXhrClient with AssetXhrClient with XhrClientThenable with OptionalResponseXhrClient with BasicAuthenticationXhrClient
```

1. `feature.framework.Support`
```scala
trait ApiAlg extends endpoint.Algebra with circe.Algebra with asset.Algebra with optinalresponse.Algebra with authentication.basic.Algebra

object Api extends ApiAlg with endpoint.play.RoutingSupport with circe.play.RoutingSupport with assets.play.RoutingSupport with optionalresponse.play.RoutingSupport with authentication.basic.play.RoutingSupport

object Api extends ApiAlg with endpoint.xhr.ClientSupport with circe.xhr.ClientSupport with asset.xhr.ClientSupport with endpoint.xhr.thenable.ClientSupport with optionalresposne.xhr.ClientSupport with suthentication.basic.xhr.ClientSupport
```

2. `feature.FrameworkSupport`
```scala
trait ApiAlg extends endpoint.Algebra with circe.Algebra with asset.Algebra with optinalresponse.Algebra with authentication.basic.Algebra

object Api extends ApiAlg with endpoint.PlayRoutingSupport with circe.PlayRoutingSupport with asset.PlayRoutingSupport with optionalresponse.PlayRoutingSupport with authentication.basic.PlayRoutingSupport

object Api extends ApiAlg with endpoint.XhrClientSupport with circe.XhrClientSupport with asset.XhrClientSupport with endpoint.XhrThenableClientSupport with optionalresposne.XhrClientSupport with suthentication.basic.XhrClientSupport
```

3. `framework.Feature`
```scala
trait ApiAlg extends algebra.Endpoints with algebra.Circe with algebra.Asset with algebra.OptionalResponse with algebra.BasicAuthentication

object Api extends ApiAlg with play.routing.Endpoint with play.routing.Circe with play.routing.Assets with play.routing.OptionalResponse with play.routing.BasicAuthentication

object Api extends ApiAlg with xhr.client.Endpoint with xhr.client.Circe with xhr.clinet.Asset with  with xhr.client.OptionalResponse with xhr.client.BasicAuthentication
```

I think all of these support more or less all the points you;ve mentioned. I personally prefer these options in order `2`, `3`, `1`. 

All translations are available [here](https://docs.google.com/spreadsheets/d/1hlJb8_Iue68OKA7zIcgIUn4TFZUS_CWL-CigtTK0afU/edit?usp=sharing)

**Comment by julienrf** [comment]
I don’t like adding a `Support` suffix everywhere.

I think I like the 3rd option. Compared to the current one it would probably give the benefit that once you’ve imported the package name of your implementation you don’t need to repeat it again and again.

**Comment by julienrf** [comment]
So, we would have the following organization:

- `endpoints` root package of the library
  - `algebra` root package of algebra interfaces
    - `Endpoints.scala` algebra interface for endpoints
    - `Assets.scala` algebra interface for assets
  - `play` root package for interpreters based on Play framework
    - `routing` root package for routing interpreters
      - `Endpoints.scala` interpreter for the `Endpoints` algebra interface
      - `Assets.scala` interpreter for the `Assets` algebra interface
    - `client` root package for client interpreters
      - `Endpoints.scala` interpreter for the `Endpoints` algebra interface
  - `xhr` root package for client interpreters based on Scala.js and `XMLHttpRequest`
    - `Assets.scala` interpreter for the `Assets` algebra interface
    - `thenable` root package for interpreters representing async results with `js.Thenable`
      - `Endpoints.scala` interpreter for the `Endpoints` algebra interface
    - `future` root package for interpreters representing async results with `scala.concurrent.Future`
      - `Endpoints.scala` interpreter for the `Endpoints` algebra interface

Does that make sense to you?

**Comment by Krever** [comment]
We could probably remove the `Support` suffix, but I think it will make classes names completely undescriptive.

> I think I like the 3rd option. Compared to the current one it would probably give the benefit that once you’ve imported the package name of your implementation you don’t need to repeat it again and again.

Yes, another benefit is that one can easily list all algebras supported by given interpreter/framework(by listing all classes in `endpoints.framework`) and also list all available interpreters(by listing all packages in `endpoints`).


> Does that make sense to you?

Yes. Would like me to implement this and make a PR?

**Comment by julienrf** [comment]
Yes, if you have time to work on that that would be awesome :)

**Comment by julienrf** [comment]
I’m closing this one. I think #10 already keeps track of the remaining work.

**Comment by Krever** [comment]
Agreed
