### ISSUE TITLE
Improve modelling of responses in endpoint algebra

### ISSUE THREAD

**Issue by afiore** [julienrf/endpoints#42]
The `endpoints.algebra` package currently models the concept of response entity, but provides no way to express two other key aspects of the response, both of them relevant to #11.

- Status codes
- Response Headers

Consider the following endpoint:

```scala
val parseInt =
   endpoint(
      post(path / "parseInt", jsonRequest[String]),
      jsonResponse[Either[String, Float]])
```
One would want to express that, for the left case (i.e. the string cannot be parsed into an integer), the server should return a 400 Bad request. While the current implementation allows defining a Circe Encoder for `Either[String, Float]`, in this case, the response status code will still be set to 200 for all the possible request entities.

I reckon that coming up with a good way to handle status codes is not trivial, as ideally, you would want the interface algebra to drive a number of different concerns: i.e. serialisation, server -client interactions, API documentation, etc. ...all of this while reducing boilerplate and keeping a high degree of flexibility!

I am still getting my head around the library and playing around with it, so I have no clear idea on how to tackle the issues above. But it sounds like an interesting challenge!

**Comment by Krever** [comment]
This certainly an interesting problem that should be adressed. 
I think that request headers are relatively easy to implement and may look for example like that:
```
val parseInt =
   endpoint(
      post(path / "parseInt", jsonRequest[String]),
      jsonResponse[Either[String, Float]]
          .withHeader[String]("foo") 
)
```

The status codes are bigger challenge as they target different responses. 
Only thing I can think of right now is something like that:
```
val parseInt =
   endpoint(
      post(path / "parseInt", jsonRequest[String]),
      jsonResponse[Float]
          .withStatusCode(200)
          .or
          .emptyResponse
          .withStatusCode(400) 
)
```
But hat may be a little tricky to implement. 

Anyway I think it is a good point for further study. IMHO we shouldn't take anything for granted, because current model is far not perfect, e.g. with current model basic authentication require special case of endpoint(`authorizedEndpoint` instead of `endpoint`) and this is not very composable.

**Comment by julienrf** [comment]
I agree that we should include response header descriptions.

For the responses’ status codes, that’s already more or less the case:

~~~ scala
endpoint(get(path / "foo"), htmlResponse) // means that we always return a 200 status code
endpoint(get(path / "foo"), option(htmlResponse)) // `option` means that the server could return 404 or the nested response
authenticatedEndpoint(get(path / "foo"), htmlResponse) // `authenticatedEndpoint` means that the server could return 401 or the nested response
~~~

However, as you pointed out, nothing describes that validating a request entity may fail (and should return a 400 status code). We also never describe that our server might return a 500 status code if an exception is thrown.

I think that we should return 400 status codes when validating a request entity fails. I remember that I tried to work on that but that was more subtle than it seems.

However, you can define your own `validated` (for instance) method that would handle the 400 response for you.

1. Define an algebra for it:

~~~ scala
def validated[A](response: Response[Either[String, A]]): Response[Either[String, A]]
~~~

2. Implement a client interpreter:

~~~ scala
def validated[A](response: Response[Either[String, A]): Response[Either[String, A]] = response
~~~

3. Implement a server interpreter:

~~~ scala
def validated[A](response: Response[Either[String, A]]): Response[Either[String, A]] =
  errorOrA =>
    response(errorOrA).left.map { r =>
      r.copy(header = r.header.copy(status = 400))
    }
~~~

4. Use it:

~~~ scala
val parseInt =
   endpoint(
      post(path / "parseInt", jsonRequest[String]),
      validated(jsonResponse[Either[String, Float]])
  )
~~~

**Comment by Krever** [comment]
With this approach, we will need separate methods for all the codes in all interpreters. Do you think there is something blocking us from creating the generic algebra(like `setStatusCode`) and then we can implement `validated`, `authenticated`, `option` and similar completely in algebra module(and interpreter only has to implement basic parts). This way we would be able to assure, that behaviors of all interpreter are consistent(to some point at least).

**Comment by Fristi** [comment]
I'm experimenting with this:

```scala
case class Error(message: String)
case class User(name: String)

case class ListUserRequest(kind: Option[String])

sealed trait ListUserResponse
case class Success(users: List[User]) extends ListUserResponse
case class BadRequest(error: Error) extends ListUserResponse
case class NotFound(error: Error) extends ListUserResponse

trait Test extends HttpEndpoints {
  def listUsers: Endpoint[ListUserRequest, ListUserResponse] = endpoint(
    request(Get, path / "test" /? optQs[String]("kind")).as[ListUserRequest],
    (
      response(200, entity = json[List[User]]).as[Success] |
      response(400, entity = json[Error]).as[BadRequest] |
      response(404, entity = json[Error]).as[NotFound] |
      cnil
    ).as[ListUserResponse]
  )

}
```

Will post when I get a compiling PoC :)

**Comment by Fristi** [comment]
For convenience I started from scratch to experiment a slighty different algebra. In `Algebra.scala` at https://github.com/Fristi/endpoints-proto, you'll find:

- Copied a lot of idea's from @julienrf library 👍 
-  `InvariantFunctor` for almost every abstract type. For encoding we use only the contravariant part and for decoding we only use the covariant part. This allows us to map complex types 
- `JsonCodec` type class which abstracts away the various json libs we use. In my opinion it would be simpler to just implement these codecs once.
- `Cocartesian` for `HttpResponse[A]` so we can choose between responses (probably by the status code, which discriminates it). We could also consider it for `HttpRequest[A]`, but in my opinion that's a rare case and we you would probably introduce a new endpoint
- `Profunctor` for `Endpoint[A, B]` since it seems to be like a function, not sure if this would be true and what we can do with it :) Not so read up on profunctors yet.

Endpoints can be seen as codecs, you'll encode data inside headers, urls and bodies which form a request. And the responses contains which can be decoded. All this data can be combined by describing it in product and coproduct types

An example of a endpoint definition;

https://github.com/Fristi/endpoints-proto/blob/master/src/main/scala/itinere/Test.scala

This compiles, but it has some problems
- For some reason the responses need in alphabetic order for shapeless `Generic` to work
- It needs parentheses around the `response` combinator otherwise we cannot combine it with `|`

Started with implementing a `Client`: https://github.com/Fristi/endpoints-proto/blob/master/src/main/scala/itinere/Client.scala, but it's a lot of work..

 Ping me if you would like to help on implementing a client/server with the new algebra.

**Comment by julienrf** [comment]
Thanks for sharing your work :)

> InvariantFunctor for almost every abstract type. For encoding we use only the contravariant part and for decoding we only use the covariant part. This allows us to map complex types

Interesting. So far I didn’t feel the need for an `imap` operation at the algebra level, though (excepted maybe for the upcoming data type schema description algebra). I wonder if it’s better to only mention functors and contravariant functors in interpreters.

> JsonCodec type class which abstracts away the various json libs we use. In my opinion it would be simpler to just implement these codecs once.

That looks interesting but I didn’t find in your code where it was used and how it works. Could you elaborate?

The current status in _endpoints_ is that we have a backend agnostic `JsonEntities` algebra that can be backed by play-json, circe, etc.

> Cocartesian for HttpResponse[A] so we can choose between responses (probably by the status code, which discriminates it). We could also consider it for HttpRequest[A], but in my opinion that's a rare case and we you would probably introduce a new endpoint

I think I understand how you can provide a useful implementation of `Cocartesian[HttpResponse]` for clients, but it’s not clear how it will work for servers.

> Profunctor for Endpoint[A, B] since it seems to be like a function, not sure if this would be true and what we can do with it :) Not so read up on profunctors yet.

I guess it’s true from the client side only (the server is dual).

**Comment by Fristi** [comment]
I've spent 6 hours at this exciting stuff :) The proof of concept is working, but I'll need more time to clean it up the coming weeks: https://github.com/Fristi/endpoints-proto/blob/master/src/main/scala/itinere/Test.scala#L17

Also there are some `???` at the `Tupler` (which uses shapeless now, but we might be able to simplify it)

> Interesting. So far I didn’t feel the need for an imap operation at the algebra level, though (excepted maybe for the upcoming data type schema description algebra). I wonder if it’s better to only mention functors and contravariant functors in interpreters.

In my implementation I use it to transform a heterogenous list and coproduct types to case classes. Aswell you can define mappings between for example a `Int` to `GameId` (wherere `GameId` is `case class GameId(id: Int) extends AnyVal`. This removes the need for defining these definitions https://github.com/Fristi/endpoints-test/blob/master/client/src/main/scala/com.veon/Client.scala#L64 and https://github.com/Fristi/endpoints-test/blob/master/server/src/main/scala/com/veon/catalog/ServerImpl.scala#L21. Also you won't need to do url encode every time you use a string, since you `imap` over the segment string implementation.

> That looks interesting but I didn’t find in your code where it was used and how it works. Could you elaborate? The current status in endpoints is that we have a backend agnostic JsonEntities algebra that can be backed by play-json, circe, etc.

`JsonCodec` is a type class which should be implemented by using libs like circe, argonaut, etc. At this line i'll define a function which pulls in the codec type class (circe, argonaut, etc)
https://github.com/Fristi/endpoints-proto/blob/master/src/main/scala/itinere/Algebra.scala#L22. Later I implement it here: https://github.com/Fristi/endpoints-proto/blob/master/src/main/scala/itinere/Test.scala#L19
The server and client are agnostic to this specific implementation. They use the intermediate `JsonCodec` https://github.com/Fristi/endpoints-proto/blob/master/src/main/scala/itinere/server/ServerJson.scala#L13

> I think I understand how you can provide a useful implementation of Cocartesian[HttpResponse] for clients, but it’s not clear how it will work for servers.

For servers it turned out quite simple: https://github.com/Fristi/endpoints-proto/blob/master/src/main/scala/itinere/server/ServerResponse.scala#L18
For client it's also simple (but tricky with PartialFunction at some call sites): https://github.com/Fristi/endpoints-proto/blob/master/src/main/scala/itinere/Client.scala#L65

> I guess it’s true from the client side only (the server is dual).

You are right, for the server it doesn't work. Client only.

**Comment by julienrf** [comment]
> In my implementation I use it to transform a heterogenous list and coproduct types to case classes

Indeed that’s definitely useful for `QueryStringParam` and `Segment`.

> For servers it turned out quite simple

Indeed that’s quite simple :) That’s very interesting we should explore this approach more.

> The server and client are agnostic to this specific implementation. They use the intermediate `JsonCodec`

It is still not clear to me how is `JsonCodec` different from `JsonResponse` and `JsonRequest` apart that it’s bidirectional.

**Comment by Fristi** [comment]
I've defined a uniform adapter interface:

```
trait JsonCodec[A] {
  def encode(entity: A): String
  def decode(input: String): String Either A
}
```

After that I define a interface `WithJsonCodec` which implicitly summons the codec type class from for example circe or argonaut and turns it into the adapter interface.

```
trait WithJsonCodec {
  type JsonCodecTypeClass[A]

  implicit def jsonCodec[A : JsonCodecTypeClass]: JsonCodec[A]
}
```

Endpoints are something which can be done over NATS, Thrift as well, so I've built http algebra on top of `Endpoint`. The `HttpJsonAlgebra` trait can be pulled in to have JSON support, something similiar could be done for XML. 

```
trait HttpJsonAlgebra { self: HttpRequestAlgebra with HttpResponseAlgebra with WithJsonCodec =>
  def jsonResponse[A : JsonCodec]: HttpResponseEntity[A]
  def jsonRequest[A : JsonCodec]: HttpRequestEntity[A]
}
```

Here you'll see that we summon the `JsonCodec` type class. The server and client both implement it. Both implementations have no clue of argonaut, circe, etc.

For a example see:

- Argonaut `JsonCodec`: https://github.com/Fristi/endpoints-proto/blob/master/json-argonaut/src/main/scala/itinere/json/argonaut/ArgonautSupport.scala
- Client JSON impl: https://github.com/Fristi/endpoints-proto/blob/master/akka-http-client/src/main/scala/itinere/client/ClientJson.scala
- Server JSON impl: https://github.com/Fristi/endpoints-proto/blob/master/akka-http-server/src/main/scala/itinere/server/ServerJson.scala

**Comment by tdroxler** [comment]
Hello, sorry to resurrect this, I'm facing the same needs, so what I currently did in my project is to add this function in my akka-http server: 
```  
def implementedByAsynchEither[A, B, E <: Error](endpoint: Endpoint[A, B])(
    implementation: A => Future[Either[E, B]]
  )(errorHandling: E => Route)(implicit executionContext: ExecutionContext): Route = endpoint.request { arguments =>
    Directives.onComplete {
      implementation(arguments).map {
        case Right(a)    => endpoint.response(a)
        case Left(error) => errorHandling(error)
      }
    } {
      case Success(result) => result
      case Failure(ex)     => Directives.complete(ex)
    }
  }
```

So two questions: 
1. Do you want me to make a PR to add this small thing in the akka-http module? 
2. How can I help for this ticket?

**Comment by julienrf** [comment]
Hello Thomas,

I wouldn’t add another `implementedByXxx` operation, but instead, I would add a response combinator like [`wheneverFound`](https://static.javadoc.io/org.julienrf/endpoints-algebra_2.12/0.8.0/endpoints/algebra/Endpoints.html#wheneverFound[A](response:Responses.this.Response[A],notFoundDocs:endpoints.algebra.Documentation):Responses.this.Response[Option[A]]) or [`wheneverValid`](http://julienrf.github.io/endpoints/guides/custom-authentication.html#algebra), which would turn a `Response[A]` into a `Response[Either[E, A]]`. This would have the advantage of making it possible to *interpret* this combinator in other interpreters (like the openapi one, for instance, to document how errors are signaled in this endpoint). Does that make sense to you?

If you end up with something that looks good I’d appreciate if you make a PR, yes!

**Comment by tdroxler** [comment]
Sure I'll try to do something in that way :+1:

**Comment by julienrf** [comment]
Hello Thomas, did you solve your problem? Or do you need some guidance?

**Comment by tdroxler** [comment]
Unfortunately I hadn't much time to work on it :tired_face:  sorry

**Comment by julienrf** [comment]
We should replace the existing `Response[A]` with a `ResponseEntity[A]`, such that `emptyResponse`, `textResponse` and `jsonResponse` only define the response **entity** but not their status. Your method would then become:

~~~ scala
def wheneverValid[A, E](response: Response[A])(errorEntity: ResponseEntity[E]): Response[Either[E, A]]
~~~

We might need to introduce the following operation too:

~~~ scala
def ok[A](entity: ResponseEntity[A]): Response[A]
~~~

Then, existing endpoint definitions would have to be updated as follows:

~~~ diff
- endpoint(get(path), textResponse())
+ endpoint(get(path), ok(textResponse())
~~~

What do you think?

I understand that it would be quite a big change… As a first step, you might want to remove the `errorResponse: Response[E]` parameter and use an error type specific to your application (no generic `E` type parameter):

~~~ scala
def wheneverValid[A](response: Response[A]): Response[Either[MyError, A]]
~~~

If that works for you, then you can generalize to arbitrary `E` error types by introducing an `errorEntity: ResponseEntity[E]` parameter.

What do you think?

**Comment by julienrf** [comment]
The work consisting of splitting responses and responses’ entities could be done separately. It would be useful on its own, anyway.

**Comment by tdroxler** [comment]
I like the `ResponseEntity` idea, it fit well with what we have with `Request` and `RequestEntity`. 

Using 
```scala
def wheneverValid[A](response: Response[A]): Response[Either[MyError, A]]
```
 work well, but it' still not really convenient for the status codes, because I need to pattern match my error in both my server and my openapi. 

So I experimented with:
```scala
trait WithCode { 
  def statusCode: Int //or proper StatusCode type
}
```
and then I define:
```scala
def wheneverValid[A, E <: WithCode](response: Response[A]): Response[Either[E, A]]
```
so then I can simply do in my server (akka):
```scala
def wheneverValid[A, E <: api.WithCode](response: Response[A]): Response[Either[E, A]] ={
    case Right(a) => response(a)
    case Left(error) => Directives.complete((error.statusCode, error))
  }
``` 
what do you think of this approach?

**Comment by julienrf** [comment]
It looks like in your example you could remove the `E` type parameter and return a `Response[Either[WithCode, A]`, no?

~~~ diff
- def wheneverValid[A, E <: WithCode](response: Response[A]): Response[Either[E, A]]
+ def wheneverValid[A](response: Response[A]): Response[Either[WithCode, A]]
~~~

And also:

~~~ diff
- def wheneverValid[A, E <: api.WithCode](response: Response[A]): Response[Either[E, A]] = {
+ def wheneverValid[A](response: Response[A]): Response[Either[api.WithCode, A]] = {
    case Right(a) => response(a)
    case Left(error) => Directives.complete((error.statusCode, error))
  }
~~~

**Comment by tdroxler** [comment]
Yes, I'll try. 

Are you fine if I go that way and try to make a PR?

**Comment by julienrf** [comment]
Yes.

**Comment by tdroxler** [comment]
I took the opportunity to start the work of splitting response entity because it endup to be easier to do this `wheneverValid` thing. The WIP is here (only for akka-http-server yet, and based on `v0.8.0` because I haven't updade to `v0.9.0` yet in my project) https://github.com/tdroxler/endpoints/commit/1f4359e1a2363c2cc8b1e43d3edca191372bdd4a This works as expected and I was happy, but then I tried the `openapi` implementation and had some problems, the quick solution I did is here https://github.com/tdroxler/endpoints/commit/d221c4069cba7039db01a8b7504c42c295873328 But I'm not happy, because it's not type safe, because you can have inconstancy between the list of code you give and the real codes that are in the error :tired_face:

**Comment by julienrf** [comment]
That looks good!

It seems that you are trying to write a more general version of what I suggested ;) If you want the status code of the invalid case to be provided in the `errorEntity` parameter, this one has to have type `Response[E]` rather than just `ResponseEntity[E]`. Then, I suggest using a different name than `wheneverValid` because one could provide a different status code than 4xx (e.g., 302, 504, etc.):

~~~ scala
def choiceResponse[A, B](respA: Response[A], respB: Response[B]): Response[Either[A, B]]
~~~

And then you can derive `wheneverValid` from this general operation:

~~~ scala
def wheneverValid[A, E](respA: Response[A])(error: ResponseEntity[E]): Response[Either[E, A]] =
  choiceResponse(response(BadRequest, error), respA)

// Generic `Response[A]` constructor
def response[A](statusCode: StatusCode, entity: ResponseEntity[A]): Response[A]
~~~

Note: the `choiceResponse` signature corresponds to what was initially proposed by @Fristi [here](https://github.com/julienrf/endpoints/issues/42#issuecomment-323513858). I used the name `choiceResponse` because the signature is similar to the one of [`choiceTagged`](https://github.com/julienrf/endpoints/blob/v0.9.0/json-schema/json-schema/src/main/scala/endpoints/algebra/JsonSchemas.scala#L131), but I don’t know if there is a more established name in the litterature (@Fristi named it “CoCartesian”).

**Comment by tdroxler** [comment]
I like both `choiceResponse[A,B]` and `response[A]` proposition and already implemented them, but it's still not convenient to define multiple error code, for example an api could return 200/400/504 for a same endpoint. We could imagine to chain `choiceResponse` but this will result in to some `Response[Either[A, Either[B, Either[C...]]]` horrible....

My idea is then to have an `enumResponse`. I did a quick test with [enumeratum](https://github.com/lloydmeta/enumeratum) and endup with something like:

```scala
  def enumResponse[A <: WithStatusCode](responseEntity: ResponseEntity[A], enum: enumeratum.Enum[A]): Response[A]
```
akka:
```scala
  override def enumResponse[A <: WithStatusCode](responseEntity: ResponseEntity[A], enum: enumeratum.Enum[A]): Response[A] = entityA =>  Directives.complete(HttpResponse(entityA.statusCode, entity = responseEntity(entityA)))
```
openapi (used enumeratum to get this `values`): 
```scala
  override def enumResponse[A <: WithStatusCode](responseEntity: ResponseEntity[A], enum: enumeratum.Enum[A]): Response[A] ={
    enum.values.toList.flatMap(a =>response(a.statusCode, responseEntity))
  }
```

This makes the work, but it's to sad to have to introduce a new lib and moreover it's easy to use with `case object`, but if you want to have an error response with a complex schema it's start to be ugly.

 The problem is always when I reach the openapi implementation, because let's say I have those possible errors: 
```scala
  sealed trait MyError extends WithStatusCode
  object MyError  {
    case class Error1(message: String) extends MyError {
      def statusCode: StatusCode = BadRequest
    }
    case class Error2(message: String, nb: Int) extends MyError {
      def statusCode: StatusCode = NotFound
    }
  }
```
 the akka implementation is never a problem, because I don't need to have the list of all possible error, but for openapi I do. 

Maybe I should stop wondering to much of the openapi and do something like: 
```scala 
  trait EnumEntry {
    def response[A]: Response[A]
  }
  trait Enum[A] {
    val responses: List[A]
  }
  sealed trait MyError extends EnumEntry
  object MyError extends Enum[MyError] {
    //If user forgot one error in the list it's his fault!!!
    val responses = List(Error1.response, Error2.response)

    case class Error1(message: String) 
    object Error1 extends MyError {
      def response = response(BadRequest, jsonResponse[Error1])
    }
    case class Error2(message: String, nb: Int) 
    object Error2 extends MyError {
      def statusCode = response(NotFound, jsonResponse[Error2])
    }
  }
```

**Comment by julienrf** [comment]
Hello Thomas,

I don't think you can implement the client interpreter with your approach.

I believe nesting Either values is the way to go. With the help of shapeless (or something similar) the boilerplate can be dramatically cut (see the examples from @Fristi)

**Comment by julienrf** [comment]
Hey Thomas,

After thinking much about it, I don’t think supporting different status codes with the same response entity always make sense. For instance, it is unlikely that your “ok” response will contain the same entity that your “bad request” response. This observation motivates the following signature:

~~~ scala
def choiceResponse[A, B](respA: Response[A], respB: Response[B]): Response[Either[A, B]]
~~~

Where each `Response` has its own status code and entity.

That being said, in my case at least, it is common to share the same entity format for all error responses (both client and server errors, btw). For instance, my error messages have the same format, whether my response status is “bad request”, “unauthorized”, “not found” or “internal server error”. That use case would motivate the following operation:

~~~ scala
def responseWithStatuses[A](statuses: Set[StatusCode], entity: ResponseEntity[A]): Response[(StatusCode, A)]
~~~

But, as you said, there is no simple way to enforce programmers to provide the same set of `statuses` that the ones they actually use on their server implementation.

Anyway, I think having `choiceResponse` would be a great improvement. If that does not fit your use case or you don’t have time to PR it, let me know and I will take care of it.

**Comment by tdroxler** [comment]
Hi Julien,

I agree on everything and indeed in my use cases, the errors always have the same format....but you know...overengineering is fun....

I didn't had time to work on it recently, but I still want to add this `choiceResponse` because it's indeed a nice thing to have. 

I'll keep you updated.
