### ISSUE TITLE
Data schema description

### ISSUE THREAD

**Issue by julienrf** [julienrf/endpoints#51]
When remote actors talk to each other, they have to agree on the format used to exchange data. Currently, the strategy to make both clients and servers agree on data formats is to use the same codec (ie. we require an implicit value which is (generally) unique for a given type to serialize). So far, the concrete types of these codecs are Circe’s `Encoder` and `Decoder` or Akka-http’s `Marshaller` and `Unmarshaller`.

We should add a new codec concrete type that describes the structure of the data so that we can generate more complete documentation of endpoints.

**Comment by ShaneDelmore** [comment]
Do you think it would be possible to have server and client negotiate if a schema is compatible instead of using the same code?  For example, if I have v1Codec[User] client and v2Codec[User] server which is identical but with a new optional field, it would be great if these were known to be compatible if it doesn’t add too much complexity.  I have seen shapeless techniques to determine if one class could be transformed to another than understood how to handle extra optional fields example.

**Comment by julienrf** [comment]
Yes, that would be possible. I would leave that to another ticket, though :)

**Comment by julienrf** [comment]
Closed by #53.
