### ISSUE TITLE
Question: expected implementations of JsonSchemas

### ISSUE THREAD

**Issue by harpocrates** [julienrf/endpoints#512]
As I understand it, part of the benefit of `algebra.JsonSchemas` is that multiple interpreters will do different things with the abstract schema information while still agreeing on exactly the same underlying JSON format. This is obviously true for the `ujson.JsonSchemas` and `openapi.JsonSchemas`, but is it expected to be true for all lawful interpreters?

To put it differently: does this mean that every combinator in `algebra.JsonSchemas` has exactly one correct interpretation in terms of the JSON that it is expected to consume/produce?

  * if so, then `algebra.JsonSchemas` would benefit from more Scaladocs specifying exactly the JSON representation expected for each combinator

  * if not, that means that `ujson.JsonSchemas` and `openapi.JsonSchemas` have an even more special relationship. To put it another way: I can't easily swap out `ujson.JsonSchemas` for another interpreter if I lose the representation equivalence guarantee with  `openapi.JsonSchemas` - my interpreter might interpret `byteJsonSchema` as a JSON string while `openapi.JsonSchemas.byteJsonSchema` represents it as a number.

**Comment by julienrf** [comment]
> To put it differently: does this mean that every combinator in `algebra.JsonSchemas` has exactly one correct interpretation in terms of the JSON that it is expected to consume/produce?

Yes.

Although only [a part](https://github.com/julienrf/endpoints/blob/5c9c60ce74db13ee3c0703a7de68f5ae96739906/json-schema/json-schema/src/test/scala/endpoints/algebra/JsonSchemasOptionalFieldsTest.scala#L8-L10) of our `JsonSchemas` tests are shared by all the interpreters. We should increase the coverage of these tests but it’s not easy because there is not (yet?) a common way to represent errors (so, each interpreter return its own error messages).

> if so, then `algebra.JsonSchemas` would benefit from more Scaladocs specifying exactly the JSON representation expected for each combinator

:100:

Over time, I found that it was useful to specify, for each operation in `algebra`, what is the expected behavior for server interpreters, client interpreters, and documentation interpreters. I try to provide this specification for new operations, but I didn’t update all the existing operations (any help is welcome!).

**Comment by harpocrates** [comment]
Thanks, that makes sense. I'll contribute some documentation if/when I get some extra time. 😄
