### ISSUE TITLE
Extend OpenApi model

### ISSUE THREAD

**Issue by bmeesters** [julienrf/endpoints#531]
The official OpenApi model offers some operations which are currently not supported by Endpoints generation. For example you can create a top level description whereas the current definition only supports a version and a title:

```scala
case class Info(
    title: String,
    version: String
    // TODO: add description field as well
)
```

Another, more involved change would be to add support for information on tags, see https://swagger.io/docs/specification/grouping-operations-with-tags/. Not only are you allowed to tag operations, you can also add additional information to these tags like you would to components. In a more complex domain, this would allow you to describe your data types in semantics, not only in structure.

**Comment by bmeesters** [comment]
@julienrf I added this issue since we need something like this in our documentation. The first is probably very simple. The latter would require to reshape tags, as they are currently only strings.

I would be willing to work on this, though it might be good to sketch a solution before coding. WDYT?

**Comment by julienrf** [comment]
I agree that we should support as many things that are supported by OpenAPI. As you said, the current model provides only partial support.

One important point (since I would like to release a 1.x version soon) is to either make the OpenAPI model complete soon or to redesign it in a way that supports adding more stuff to it in a backward-compatible way. This means using plain classes instead of case classes (we can see an example of a design that supports backward-compatible evolutions in [sbt-contraband](https://www.scala-sbt.org/contraband/code-generation.html#Record+types), for instance).

About tags, the idea would to use [this model](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#tagObject) instead of just strings or is there anything else that I missed?

To ease migration, it would be better if we could still provide the existing API for adding tags and constructing the `Info`. ie, code like this should still compile:

~~~ scala
val someResource =
  endpoint(
    get(path / "some-resource"),
    ok(textResponse),
    docs = EndpointDocs(description = Some("The contents of some resource"), tags = List("foo"))
  )

val docs = openApi(Info("Title", "0.0.0"))(someResource)
~~~

Does that make sense?

I know that redesigning the OpenAPI model would require a significant effort comparing to just adding a  `description` field, but would you be interested in doing that?

**Comment by bmeesters** [comment]
Yes I can understand your concerns. IMO it makes sense to change de OpenApi model so that it remains backwards compatible once new things are added. Have you thought about also doing something with abstract types and the OpenApi model? Not sure if that is feasible, but it is one of the strengths of _endpoints_ that you can also update your data model.

It would probably still make sense to rewrite the case classes to normal classes. I can give it a shot, probably in the first step just the rewrite to classes and only thereafter an updated model.

I also think it should be possible to keep the API as is w.r.t. just using tags as strings. Then maybe the `openApi` function should also have an optional tags parameter so you can add the richer documented tags. If a string tag used does not appear in that list it will just show the string as it would do now, is that okay?

```scala
val myTag = tag(description = Some("myDescription")
openApi(Info("Title", "0.0.0"))(someResource)(myTag) // Not sure if currying is the right approach
```

**Comment by julienrf** [comment]
> Have you thought about also doing something with abstract types and the OpenApi model?

The thing is that the OpenAPI model is needed by the `openapi` *interpreter*, not the algebra. So, it has to be concrete (or we will just add yet another level of indirection, which might not be convenient to use).

> Then maybe the `openApi` function should also have an optional tags parameter so you can add the richer documented tags. If a string tag used does not appear in that list it will just show the string as it would do now, is that okay?

Yes, what about these slight variations, though?

~~~ scala
// In the endpoint descriptions
val myTag = "my-tag"
val index = endpoint(get(path), ok(textResponse), docs = EndpointDocs(tags = List(myTag)))
// And then, when interpreting as documentation
val tags = List(
  tag(name = myTag, description = Some("my description"))
)
openApi(Info(...), tags)(index)
~~~

The idea is that users don’t have to write the tag name again and again, thus preventing them from mispelling it.

Alternatively, we could support defining the tag itself at the same place we define the endpoints (instead of defining it at the point we interpret the endpoints as documentation):

~~~ scala
// In the endpoint descriptions
val myTag = tag("my-tag", Some("my-description"))
val index = endpoint(get(path), ok(textResponse), docs = EndpointDocs(tags = List(myTag)))
// And then, when interpreting as documentation
openApi(Info(...), tags = List(myTag))(index)
~~~

**Comment by bmeesters** [comment]
> The thing is that the OpenAPI model is needed by the openapi interpreter, not the algebra

Makes sense, I was trying to explore ideas, but this might be a bad one.

> The idea is that users don’t have to write the tag name again and again, thus preventing them from mispelling it.

Right, but this will always be a convention right, since you can't really enforce it? Might be good to document it though.

> Alternatively, we could support defining the tag itself at the same place we define the endpoints

I quite like this. But that would require changing the API of defining tags compared to the status quo, so I am not sure if that works for you?

**Comment by julienrf** [comment]
> Do you have any ideas on how to support both versions?

Let’s try to not use implicit conversions for that. I would have two constructors for `EndpointDocs`:

~~~ scala
class EndpointDocs(summary: Documentation, description: Documentation, tags: Seq[Tag]) {
}

object EndpointDocs {
  // Alternate constructor with just tag names
  def this(summary: Documentation, description: Documentation, tags: Seq[String]) {
    this(summary, description, tags.map(Tag(_, description = None)))
  }
}
~~~

**Comment by bmeesters** [comment]
> Let’s try to not use implicit conversions for that. I would have two constructors for EndpointDocs

Yes I also wouldn't want to rely on implicit conversions, I just couldn't really think of another solution. I initially thought he Tag type would be abstract, so then two constructors wouldn't work if I recall correctly because of type erasure. But if Tag is concrete then I that should work.

**Comment by bmeesters** [comment]
So, to conclude:

1. We want a PR changing the OpenAPI model to using classes instead of case classes.
2. We want another PR to update the OpenAPI model with a description on the top level & a complex type representing tags. This should also include means to create tags and their structure in the algebra without breaking current behavior. This is possible by providing multiple constructors for `EndpointDocs`.

The new tag will look like this (though with normal classes, but left out for brevity):
```scala
case class Tag(
  name: String,
  description: Option[String] = None,
  externalDocs: Option[ExternalDocumentationObject] = None
)

// Or Uri instead of URL?
case class ExternalDocumentationObject(url: String, description: Option[String] = None)
```

Is this a correct summary @julienrf ?

**Comment by julienrf** [comment]
Yes! :ok_hand:

**Comment by bmeesters** [comment]
Thinking a bit more about it, how would we deal with two or more endpoints that share a tag? I don't thinking repeating the same tag description over and over is a good idea. Though, by providing it once, you might overwrite the one you actually want to keep if we choose a "winner". 

I personally see two solutions.

1. Provide the tag payloads separately from the endpoints (my earlier proposal). 
2. Provide a way to separate a tag name (reference) from its payload.I.e. allow users to either provide a String (reference to a tag), or a Payload (the full tag). Providing two payloads for a the same tag name would result in an exception. 

Solution 1. makes it easier to use endpoints as you would today, with an opt-in for richer tags. But solution 2. doesn't require you to separate the tags from the endpoints itself. WDYT @julienrf?

**Comment by julienrf** [comment]
I think it’s reasonable to expect (and encourage) users to define tags as vals and reuse them in all their endpoints. In case we detect a mismatch (two tags with the same name but not the same description or external docs) we can throw an exception or just log an error and pick one.

**Comment by bmeesters** [comment]
Alright, seems also reasonable to me. I can start on this next week, I am a bit busy this week.
